##### BEST PRACTICES
1. Preprocessing and Cleaning
2. Train Test Split
3. BOW, TF-IDF, Word2Vec
4. Train ML Algorithm

In [5]:
## Load the Dataset
import pandas as pd
df = pd.read_csv("all_kindle_review.csv")
df.head()

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000

In [8]:
data=df[["reviewText","rating"]]
data

                                              reviewText  rating
0      Jace Rankin may be short, but he's nothing to ...       3
1      Great short read.  I didn't want to put it dow...       5
2      I'll start by saying this is the first of four...       3
3      Aggie is Angela Lansbury who carries pocketboo...       3
4      I did not expect this type of book to be in li...       4
...                                                  ...     ...
11995  Valentine cupid is a vampire- Jena and Ian ano...       4
11996  I have read all seven books in this series. Ap...       5
11997  This book really just wasn't my cuppa.  The si...       3
11998  tried to use it to charge my kindle, it didn't...       1
11999  Taking Instruction is a look into the often hi...       3

[12000 rows x 2 columns]

In [9]:
data.shape

(12000, 2)

In [13]:
## Find missing values
data["rating"].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [15]:
## Preprocessing and Cleaning
data['rating'] = data['rating'].apply(lambda x: 0 if x<3 else 1)
data

C:\Users\saakh\AppData\Local\Temp\ipykernel_15980\3229217266.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['rating'] = data['rating'].apply(lambda x: 0 if x<3 else 1)

                                              reviewText  rating
0      Jace Rankin may be short, but he's nothing to ...       1
1      Great short read.  I didn't want to put it dow...       1
2      I'll start by saying this is the first of four...       1
3      Aggie is Angela Lansbury who carries pocketboo...       1
4      I did not expect this type of book to be in li...       1
...                                                  ...     ...
11995  Valentine cupid is a vampire- Jena and Ian ano...       1
11996  I have read all seven books in this series. Ap...       1
11997  This book really just wasn't my cuppa.  The si...       1
11998  tried to use it to charge my kindle, it didn't...       0
11999  Taking Instruction is a look into the often hi...       1

[12000 rows x 2 columns]

In [16]:
## 1. Lower all the cases
data['reviewText'] = data['reviewText'].str.lower()

C:\Users\saakh\AppData\Local\Temp\ipykernel_15980\3880643322.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['reviewText'] = data['reviewText'].str.lower()

In [17]:
data.head()

                                          reviewText  rating
0  jace rankin may be short, but he's nothing to ...       1
1  great short read.  i didn't want to put it dow...       1
2  i'll start by saying this is the first of four...       1
3  aggie is angela lansbury who carries pocketboo...       1
4  i did not expect this type of book to be in li...       1

In [ ]:
!pip install BS4

Requirement already satisfied: BS4 in .\.venv\Lib\site-packages (0.0.2)
Requirement already satisfied: beautifulsoup4 in .\.venv\Lib\site-packages (from BS4) (4.14.3)
Requirement already satisfied: soupsieve>=1.6.1 in .\.venv\Lib\site-packages (from beautifulsoup4->BS4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in .\.venv\Lib\site-packages (from beautifulsoup4->BS4) (4.15.0)
Collecting lxml
  Downloading lxml-6.0.2-cp312-cp312-win_amd64.whl.metadata (3.7 kB)
Downloading lxml-6.0.2-cp312-cp312-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 8.5 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 16.0 MB/s  0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.0.2

In [ ]:
!pip install lxml
def clean_dataset(df):
    '''
    Cleaning dataset:
    1. by lowering the case
    2. by removing special characters
    3. Apply lematizer
    '''
    import re
    import nltk
    from bs4 import BeautifulSoup
    from nltk.corpus import stopwords
    from nltk.stem import WordNetLemmatizer

    lemmatizer = WordNetLemmatizer()

    def lemmatizer_words(txt):
        return " ".join([lemmatizer.lemmatize(word) for word in txt.split()])

    nltk.download('stopwords') 
    df = df.copy()
    df['reviewText'] = df['reviewText'].str.lower()

    df['reviewText'] = df['reviewText'].apply(lambda x:re.sub('[^a-z A-Z 0-9-]','',x))
    df['reviewText'] = df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
    df['reviewText']=df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))
    ## Remove html tags
    df['reviewText']=df['reviewText'].apply(lambda x: BeautifulSoup(x, 'html.parser').get_text())
    ## Remove any additional spaces
    df['reviewText']=df['reviewText'].apply(lambda x: " ".join(x.split()))



    return df

Requirement already satisfied: lxml in .\.venv\Lib\site-packages (6.0.2)

In [31]:
data = clean_dataset(data)
data.head()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\saakh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

                                          reviewText  rating
0  jace rankin may short hes nothing mess man hau...       1
1  great short read didnt want put read one sitti...       1
2  ill start saying first four books wasnt expect...       1
3  aggie angela lansbury carries pocketbooks inst...       1
4  expect type book library pleased find price right       1